import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { QRCodeSVG } from 'qrcode.react';
import { ArrowDownLeft, ArrowUpRight, BarChart3, Check, ChevronRight, Clipboard, Copy, ExternalLink, FileText, Link2, Plus, QrCode, ReceiptText, RefreshCw, Search, Send, ShieldCheck, Sparkles, WalletCards, X } from 'lucide-react';
import './styles.css';
import './flowra-enhancements.css';
import type { Payment, PaymentStatus } from './lib/types';
import { loadPayments, savePayments } from './lib/storage';
import { buildPaymentUrl, summarizePayments } from './lib/ledger';
import { connectArcWallet, sendUSDC, type WalletConnection } from './lib/arcKit';
import { verifyUSDCTransfer } from './lib/verify';

function makeId(prefix: string) { return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`; }
function short(value?: string, left = 8, right = 6) { if (!value) return '—'; return value.length > left + right + 1 ? `${value.slice(0, left)}…${value.slice(-right)}` : value; }

function App() {
  const [payments, setPayments] = useState<Payment[]>(() => loadPayments());
  const [tab, setTab] = useState<'overview'|'payments'|'invoices'|'settings'>('overview');
  const [wallet, setWallet] = useState<WalletConnection | null>(null);
  const [busy, setBusy] = useState(false);
  const [toast, setToast] = useState('');
  const [modal, setModal] = useState<'request'|'invoice'|'send'|'receive'|'details'|null>(null);
  const [selected, setSelected] = useState<Payment | null>(null);
  const stats = summarizePayments(payments);
  const nav = [['overview','Overview',BarChart3],['payments','Payments',WalletCards],['invoices','Invoices',FileText],['settings','Settings',ShieldCheck]] as const;
  useEffect(() => { if (new URLSearchParams(window.location.search).has('pay')) setModal('send'); }, []);
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(''), 2600); }
  function updatePayment(id: string, patch: Partial<Payment>) { setPayments(current => { const next=current.map(p=>p.id===id?{...p,...patch}:p); savePayments(next); return next; }); }
  function addPayment(payment: Payment) { setPayments(current => { const next=[payment,...current]; savePayments(next); return next; }); setModal(null); notify('Saved to FLOWRA.'); }
  async function handleConnect() { setBusy(true); try { const c=await connectArcWallet(); setWallet(c); notify(`Connected: ${short(c.address,6,4)}`); } catch(e) { notify(e instanceof Error?e.message:'Wallet connection failed.'); } finally { setBusy(false); } }
  async function handleSend(to:string,amount:string,note:string,reference?:string) { if(!wallet) throw new Error('Connect an Arc-compatible browser wallet first.'); setBusy(true); try { const result=await sendUSDC(wallet,to,amount); const txHash=result?.steps?.find((step:any)=>step?.txHash)??result?.txHash; if(!txHash) throw new Error('Wallet did not return a transaction hash.'); const payment:Payment={id:makeId('pay'),type:'payment',reference:reference||`PAY-${Date.now().toString().slice(-6)}`,counterparty:to,amount,token:'USDC',status:'processing',createdAt:new Date().toISOString(),txHash,wallet:wallet.address,note}; addPayment(payment); setSelected(payment); setModal('details'); notify('Transaction submitted. Verify it on-chain to complete payment.'); } catch(e) { notify(e instanceof Error?e.message:'Payment failed.'); } finally { setBusy(false); } }
  async function handleVerify(payment:Payment) { if(!payment.txHash) return; setBusy(true); try { const result=await verifyUSDCTransfer(payment.txHash as `0x${string}`,payment.counterparty,payment.amount,payment.type==='payment'?payment.wallet:undefined); const patch:Partial<Payment>={status:result.reconciled?'paid':'exception',verifiedAt:result.verified?new Date().toISOString():undefined,reconciledAt:result.reconciled?new Date().toISOString():undefined,verification:result}; updatePayment(payment.id,patch); setSelected({...payment,...patch}); notify(result.reason); } catch(e) { notify(e instanceof Error?e.message:'Could not verify transaction yet.'); } finally { setBusy(false); } }
  const recent=payments.slice(0,8);
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><span>F</span></div><div><strong>FLOWRA</strong><small>simple global payments</small></div></div><nav>{nav.map(([id,label,Icon])=><button className={tab===id?'nav-item active':'nav-item'} key={id} onClick={()=>setTab(id)}><Icon size={18}/><span>{label}</span>{tab===id&&<ChevronRight size={15} className="nav-chevron"/>}</button>)}</nav><div className="sidebar-foot"><div className="network-dot"><span/> Arc Testnet</div><p>Circle App Kit powered</p></div></aside>
  <main className="main"><header className="topbar"><div><span className="eyebrow">Payment workspace</span><h1>{tab==='overview'?'Good to see you.':tab[0].toUpperCase()+tab.slice(1)}</h1></div><button className="connect-btn" onClick={handleConnect} disabled={busy}><WalletCards size={17}/>{wallet?short(wallet.address,6,4):'Connect wallet'}</button></header>
  {tab==='overview'&&<><section className="hero"><div><span className="pill"><Sparkles size={14}/> Built around real payment flows</span><h2>Move money.<br/>Know what happened.</h2><p>Receive, send, request, invoice and reconcile USDC payments with Arc settlement and Circle App Kit.</p><div className="hero-actions"><button className="primary" onClick={()=>setModal('request')}><Plus size={17}/> Request payment</button><button className="secondary" onClick={()=>setModal('send')}><Send size={17}/> Send USDC</button></div></div><div className="proof-card"><div className="proof-head"><span>Payment proof</span><span className="status-dot">TESTNET</span></div><div className="proof-amount">{stats.received.toLocaleString(undefined,{maximumFractionDigits:2})}<span> USDC</span></div><div className="proof-row"><span>Settlement</span><b>Arc Testnet</b></div><div className="proof-row"><span>Wallet</span><b>{wallet?short(wallet.address,8,4):'Not connected'}</b></div><div className="proof-row"><span>Verification</span><b className="ok"><Check size={14}/> On-chain</b></div></div></section>
  <section className="stats-grid"><Stat label="Received" value={`${stats.received.toLocaleString(undefined,{maximumFractionDigits:2})} USDC`} icon={ArrowDownLeft}/><Stat label="Sent" value={`${stats.sent.toLocaleString(undefined,{maximumFractionDigits:2})} USDC`} icon={ArrowUpRight}/><Stat label="Pending" value={`${stats.pending}`} icon={ReceiptText}/><Stat label="Needs attention" value={`${stats.exceptions}`} icon={ShieldCheck}/></section>
  <section className="content-grid"><div className="panel"><div className="panel-title"><div><span className="eyebrow">Activity</span><h3>Recent payments</h3></div><button className="link-btn" onClick={()=>setTab('payments')}>View all <ChevronRight size={15}/></button></div>{recent.length?<PaymentTable payments={recent} onOpen={p=>{setSelected(p);setModal('details')}}/>:<EmptyState onAction={()=>setModal('request')}/>}</div><div className="panel side-panel"><div className="panel-title"><div><span className="eyebrow">Quick actions</span><h3>Get paid faster</h3></div></div><QuickAction icon={Link2} title="Payment link" text="Share one link to collect USDC." onClick={()=>setModal('request')}/><QuickAction icon={QrCode} title="Receive QR" text="Show your Arc receive address." onClick={()=>setModal('receive')}/><QuickAction icon={FileText} title="Invoice" text="Create a payment-ready invoice." onClick={()=>setModal('invoice')}/></div></section></>}
  {tab==='payments'&&<PaymentsPage payments={payments} onSend={()=>setModal('send')} onOpen={p=>{setSelected(p);setModal('details')}} onVerify={handleVerify}/>} {tab==='invoices'&&<InvoicesPage payments={payments} onNew={()=>setModal('invoice')} onOpen={p=>{setSelected(p);setModal('details')}}/>} {tab==='settings'&&<SettingsPage wallet={wallet} onConnect={handleConnect}/>}</main>
  {modal==='request'&&<RequestModal wallet={wallet} onClose={()=>setModal(null)} onSave={addPayment}/>} {modal==='invoice'&&<InvoiceModal wallet={wallet} onClose={()=>setModal(null)} onSave={addPayment}/>} {modal==='send'&&<SendModal onClose={()=>setModal(null)} onSend={handleSend} busy={busy} connected={!!wallet}/>} {modal==='receive'&&<ReceiveModal wallet={wallet} onConnect={handleConnect} onClose={()=>setModal(null)}/>} {modal==='details'&&selected&&<DetailsModal payment={selected} onClose={()=>setModal(null)} onVerify={handleVerify} busy={busy}/>} {toast&&<div className="toast">{toast}</div>}
  </div>;
}
function Stat({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="stat-card"><div className="stat-icon"><Icon size={17}/></div><span>{label}</span><strong>{value}</strong></div>}
function QuickAction({icon:Icon,title,text,onClick}:{icon:any;title:string;text:string;onClick:()=>void}){return <button className="quick-action" onClick={onClick}><div className="quick-icon"><Icon size={17}/></div><div><b>{title}</b><p>{text}</p></div><ChevronRight size={16}/></button>}
function EmptyState({onAction}:{onAction?:()=>void}){return <div className="empty"><WalletCards size={22}/><b>No payments yet</b><p>Connect a wallet, request a payment, or create an invoice to start.</p>{onAction&&<button className="secondary" onClick={onAction}>Create payment request</button>}</div>}
function PaymentTable({payments,onOpen,onVerify}:{payments:Payment[];onOpen:(p:Payment)=>void;onVerify?:(p:Payment)=>void}){return <div className="table-wrap"><table><thead><tr><th>Payment</th><th>Counterparty</th><th>Amount</th><th>Status</th><th/></tr></thead><tbody>{payments.map(p=><tr key={p.id} onClick={()=>onOpen(p)}><td><b>{p.reference}</b><small>{new Date(p.createdAt).toLocaleString()}</small></td><td><span className="mono">{short(p.counterparty)}</span></td><td><b>{p.amount} USDC</b></td><td><Status status={p.status}/></td><td>{onVerify&&p.txHash&&['processing','exception'].includes(p.status)?<button className="table-action" onClick={e=>{e.stopPropagation();onVerify(p)}} title="Verify on-chain"><RefreshCw size={14}/></button>:<ChevronRight size={15}/>}</td></tr>)}</tbody></table></div>}
function Status({status}:{status:PaymentStatus}){const label={paid:'Paid',processing:'Processing',pending:'Pending',exception:'Exception',failed:'Failed'}[status];return <span className={`status ${status}`}><span/>{label}</span>}
function PaymentsPage({payments,onSend,onOpen,onVerify}:{payments:Payment[];onSend:()=>void;onOpen:(p:Payment)=>void;onVerify:(p:Payment)=>void}){const[q,setQ]=useState('');const filtered=useMemo(()=>payments.filter(p=>`${p.reference} ${p.counterparty} ${p.amount} ${p.note||''}`.toLowerCase().includes(q.toLowerCase())),[payments,q]);return <section className="page"><div className="page-head"><div><span className="eyebrow">Ledger</span><h2>All payments</h2><p>Every request, invoice and transaction recorded by FLOWRA.</p></div><button className="primary" onClick={onSend}><Send size={17}/> Send USDC</button></div><div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reference, address, amount…"/></div></div>{filtered.length?<PaymentTable payments={filtered} onOpen={onOpen} onVerify={onVerify}/>:<EmptyState/>}</section>}
function InvoicesPage({payments,onNew,onOpen}:{payments:Payment[];onNew:()=>void;onOpen:(p:Payment)=>void}){const invoices=payments.filter(p=>p.type==='invoice');return <section className="page"><div className="page-head"><div><span className="eyebrow">Collections</span><h2>Invoices</h2><p>Create payment-ready invoices and track reconciliation.</p></div><button className="primary" onClick={onNew}><Plus size={17}/> New invoice</button></div>{invoices.length?<PaymentTable payments={invoices} onOpen={onOpen}/>:<EmptyState onAction={onNew}/>}</section>}
function SettingsPage({wallet,onConnect}:{wallet:WalletConnection|null;onConnect:()=>void}){return <section className="page"><div className="page-head"><div><span className="eyebrow">Infrastructure</span><h2>Settings</h2><p>FLOWRA is configured for Arc Testnet using Circle App Kit.</p></div></div><div className="settings-grid"><div className="settings-card"><div className="proof-row"><span>Network</span><b>Arc Testnet · 5042002</b></div><div className="proof-row"><span>USDC</span><b className="mono">0x3600…0000</b></div><div className="proof-row"><span>Integration</span><b>Circle App Kit</b></div><div className="proof-row"><span>Wallet</span><b>{wallet?`${wallet.walletName} · ${short(wallet.address,10,4)}`:'Not connected'}</b></div>{!wallet&&<button className="primary full" onClick={onConnect}><WalletCards size={17}/> Connect wallet</button>}</div><div className="settings-card"><h3>Security & verification</h3><p className="muted">User-signed transactions stay in the browser wallet path. FLOWRA never asks for a private key, seed phrase, Circle API key or entity secret.</p><div className="security-note"><ShieldCheck size={17}/><span>Confirmed payments are reconciled against the Arc USDC Transfer event, recipient and exact 6-decimal amount.</span></div></div></div></section>}
function ModalShell({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><div><span className="eyebrow">FLOWRA</span><h3>{title}</h3></div><button className="icon-btn" onClick={onClose} aria-label="Close"><X size={18}/></button></div>{children}</div></div>}
function RequestModal({wallet,onClose,onSave}:{wallet:WalletConnection|null;onClose:()=>void;onSave:(p:Payment)=>void}){const[amount,setAmount]=useState('');const[name,setName]=useState('');const[note,setNote]=useState('');const ref=`REQ-${Date.now().toString().slice(-6)}`;const url=buildPaymentUrl(window.location.origin,{reference:ref,amount:amount||'0',counterparty:name||'payer',note,wallet:wallet?.address});const submit=()=>{if(!wallet||!/^\d+(\.\d{1,6})?$/.test(amount)||Number(amount)<=0||!name.trim())return;onSave({id:makeId('req'),type:'request',reference:ref,counterparty:name.trim(),amount,token:'USDC',status:'pending',createdAt:new Date().toISOString(),note,wallet:wallet.address,paymentUrl:url})};return <ModalShell title="Request payment" onClose={onClose}>{!wallet&&<p className="form-warning">Connect your wallet first so the payment request contains a real Arc receiving address.</p>}<label>Customer / payer<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Acme Studio"/></label><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="100.00"/></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Invoice, service, order…"/></label><div className="share-grid"><div className="link-preview"><Link2 size={16}/><span>{url}</span><button onClick={()=>navigator.clipboard?.writeText(url)} aria-label="Copy payment link"><Clipboard size={15}/></button></div><div className="qr-mini"><QRCodeSVG value={url} size={94} includeMargin/></div></div><button className="primary full" onClick={submit} disabled={!wallet}>Create payment request</button></ModalShell>}
function InvoiceModal({wallet,onClose,onSave}:{wallet:WalletConnection|null;onClose:()=>void;onSave:(p:Payment)=>void}){const[amount,setAmount]=useState('');const[client,setClient]=useState('');const[note,setNote]=useState('');const ref=`INV-${Date.now().toString().slice(-6)}`;const submit=()=>{if(!wallet||!/^\d+(\.\d{1,6})?$/.test(amount)||Number(amount)<=0||!client.trim())return;const paymentUrl=buildPaymentUrl(window.location.origin,{reference:ref,amount,counterparty:client.trim(),note,wallet:wallet.address});onSave({id:makeId('inv'),type:'invoice',reference:ref,counterparty:client.trim(),amount,token:'USDC',status:'pending',createdAt:new Date().toISOString(),note,wallet:wallet.address,paymentUrl})};return <ModalShell title="Create invoice" onClose={onClose}>{!wallet&&<p className="form-warning">Connect your wallet first so this invoice can receive USDC.</p>}<label>Client<input value={client} onChange={e=>setClient(e.target.value)} placeholder="Client name"/></label><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="500.00"/></label><label>Description<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Project milestone / service"/></label><div className="invoice-proof"><ReceiptText size={18}/><div><b>{amount||'0.00'} USDC</b><span>Payment-ready invoice</span></div></div><button className="primary full" onClick={submit} disabled={!wallet}>Create invoice</button></ModalShell>}
function SendModal({onClose,onSend,busy,connected}:{onClose:()=>void;onSend:(to:string,amount:string,note:string,reference?:string)=>Promise<void>;busy:boolean;connected:boolean}){const params=new URLSearchParams(window.location.search);const[reference]=useState(params.get('pay')||'');const[to,setTo]=useState(params.get('to')||'');const[amount,setAmount]=useState(params.get('amount')||'');const[note,setNote]=useState(params.get('note')||'');const[recipientName]=useState(params.get('name')||'');const submit=async()=>{if(!/^0x[a-fA-F0-9]{40}$/.test(to)||!/^\d+(\.\d{1,6})?$/.test(amount)||Number(amount)<=0)return;await onSend(to,amount,note,reference||undefined)};return <ModalShell title={reference?'Pay FLOWRA request':'Send USDC'} onClose={onClose}>{reference&&<div className="request-context"><span>{recipientName||'Payment request'}</span><b>{amount||'0.00'} USDC</b><small>{reference}</small></div>}<div className="chain-banner"><span>Arc Testnet</span><b>USDC native gas</b></div><label>Recipient wallet<input value={to} onChange={e=>setTo(e.target.value)} placeholder="0x…" autoCapitalize="none"/></label><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="10.00"/></label><label>Note (optional)<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Payment note"/></label>{!connected&&<p className="form-warning">Connect your browser wallet before sending.</p>}<button className="primary full" onClick={submit} disabled={busy||!connected}>{busy?'Waiting for wallet…':<><Send size={17}/> Review and send</>}</button></ModalShell>}
function ReceiveModal({wallet,onConnect,onClose}:{wallet:WalletConnection|null;onConnect:()=>void;onClose:()=>void}){const address=wallet?.address||'';return <ModalShell title="Receive USDC" onClose={onClose}>{wallet?<><div className="receive-box"><QRCodeSVG value={address} size={190} includeMargin/><b>Arc Testnet</b><span className="mono">{address}</span></div><button className="secondary full" onClick={()=>navigator.clipboard?.writeText(address)}><Copy size={16}/> Copy receive address</button></>:<><div className="empty compact"><WalletCards size={22}/><b>Connect your wallet</b><p>Your Arc address becomes your receive address.</p></div><button className="primary full" onClick={onConnect}><WalletCards size={17}/> Connect wallet</button></>}</ModalShell>}
function DetailsModal({payment,onClose,onVerify,busy}:{payment:Payment;onClose:()=>void;onVerify:(p:Payment)=>void;busy:boolean}){const explorer=payment.txHash?`https://testnet.arcscan.app/tx/${payment.txHash}`:'';return <ModalShell title={payment.reference} onClose={onClose}><div className="detail-status"><Status status={payment.status}/><b>{payment.amount} USDC</b></div><div className="detail-list"><div><span>Type</span><b>{payment.type}</b></div><div><span>Counterparty</span><b className="mono">{short(payment.counterparty,12,8)}</b></div><div><span>Created</span><b>{new Date(payment.createdAt).toLocaleString()}</b></div><div><span>Verification</span><b>{payment.verifiedAt?'Verified':'Not verified'}</b></div><div><span>Reconciliation</span><b>{payment.reconciledAt?'Matched':'Not reconciled'}</b></div>{payment.txHash&&<div><span>Transaction</span><b className="mono">{short(payment.txHash,12,10)}</b></div>}{payment.verification?.blockNumber&&<div><span>Block</span><b>{payment.verification.blockNumber}</b></div>}</div>{payment.txHash&&<div className="detail-actions"><button className="primary full" onClick={()=>onVerify(payment)} disabled={busy}><RefreshCw size={16}/>{busy?'Verifying…':'Verify & reconcile on Arc'}</button><a className="secondary full" href={explorer} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Open Arc explorer</a></div>}{payment.paymentUrl&&<button className="secondary full" onClick={()=>navigator.clipboard?.writeText(payment.paymentUrl!)}><Copy size={16}/> Copy payment link</button>}</ModalShell>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
